name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install mypy
        run: |
          python -m pip install --upgrade pip
          pip install mypy
      - name: Run mypy
        env:
          PYTHONPATH: src
        run: mypy src
