name: mypy

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install mypy
        run: pip install mypy==1.11.1

      - name: Run mypy
        run: mypy src
